public struct GameRequirementsTracker {
    public init() {}
    
    public func exitKeys() -> Bool                      { false }
    public func interactiveMap() -> Bool                { false }
    public func mainMenu() -> Bool                      { false }
    public func levelSelection() -> Bool                { false }
    public func portals() -> Bool                       { false }
    public func breaking() -> Bool                      { false }
    public func iOSAndmacOSCompatibility() -> Bool      { false }
    public func togglePause() -> Bool                   { false }
    public func implementedLevelIdeas() -> Bool         { false }
    public func autoGameSaveAndLoad() -> Bool           { false }
    public func allSpecialsImplemented() -> Bool        { false }
    public func draggableAndRotatingItems() -> Bool     { false }
    public func startWithLevel() -> Bool                { false }
    public func shootBall() -> Bool                     { false }
    public func returnBall() -> Bool                    { true  }
    public func nextLevel() -> Bool                     { false }
    public func returnToMainMenu() -> Bool              { false }
    public func shootHook() -> Bool                     { false }
    public func toggleActivateBall() -> Bool            { false }
    public func zoomFeatures() -> Bool                  { false }
    public func showPowerLevel() -> Bool                { false }
    public func associateBehaviorsWithSKNodes() -> Bool { false }
    public func draggingOnlyOneSKNodeAtATime() -> Bool  { false }
    public func HUD() -> Bool                           { false }
    public func photoshopLevelTemplate() -> Bool        { true  }
    public func ballDesign() -> Bool                    { false }
    public func pipeDesign() -> Bool                    { false }
    public func blockDesign() -> Bool                   { false }
    public func aspectRatioBoxes() -> Bool              { false }
    public func createdUniqueTypefaceForGame() -> Bool  { false }
    public func sksTemplateMade() -> Bool               { false }
    public func autoExportPhotoshopAssets() -> Bool     { false }
    public func jetpacks() -> Bool                      { false }
    public func wideLevels() -> Bool                    { false }
    public func pipeMustBeUnlocked() -> Bool            { false }
    public func blowingAir() -> Bool                    { false }
    public func limitedShots() -> Bool                  { false }
    public func limitedTime() -> Bool                   { false }
    public func certainViewAreasLocked() -> Bool        { false }
    public func rollswhereLogo() -> Bool                { false }
    public func electricGate() -> Bool                  { false }
    public func shrinkingBall() -> Bool                 { false }
    public func growingBall() -> Bool                   { false }
    public func ballCanPassBlockWhenActivated() -> Bool { false }
    public func mvp() -> Bool                           { false }
    public func windowDesigns() -> Bool                 { false }
    public func atLeast100Levels() -> Bool              { false }
    public func movingFixedBlocks() -> Bool             { false }
    public func ramps() -> Bool                         { false }
    public func chains() -> Bool                        { false }
    public func trains() -> Bool                        { false }
    public func speedBoost() -> Bool                    { false }
    public func trampoline() -> Bool                    { false }
    public func roughAndSlipperySurfaces() -> Bool      { false }
    public func water() -> Bool                         { false }
    public func lava() -> Bool                          { false }
    public func seasons() -> Bool                       { false }
    public func organizeLevelsIntoChapters() -> Bool    { false }
}
